"use client";
import type { Project, Task, Customer, ClientSite } from "@/lib/supabase/types";
import { Button } from "@/components/ui/button";
import { PROJECT_STATUS_LABEL } from "@/lib/agency";
import { EmptyState } from "@/components/ui/empty-state";
export function AgencyProduction({projects,tasks,customers,sites,onProject,onTask,onNavigate}:{projects:Project[];tasks:Task[];customers:Customer[];sites:ClientSite[];onProject:(id:string,patch:Partial<Project>)=>Promise<void>;onTask:(id:string,patch:Partial<Task>)=>Promise<void>;onNavigate:(tab:string,id?:string)=>void}){
 const stages:Project["status"][]=["in_progress","done","maintenance"];
 return <section className="pf-workflow"><p className="pf-eyebrow">PRODUCTION WEB</p><h2 className="mt-2 text-2xl font-bold">Livrer, maintenir, renouveler.</h2><p className="mt-2 text-sm text-muted">Les tâches, échéances et services restent rattachés au client et au projet.</p>{projects.length===0?<EmptyState icon="↗" title="Votre production commence ici" description="Créez un projet lié à un client pour suivre sa livraison et sa maintenance." action={<Button onClick={()=>onNavigate("projects")}>Créer un projet</Button>}/>:<div className="pf-board">{stages.map(stage=><div className="pf-lane" key={stage}><h3>{PROJECT_STATUS_LABEL[stage].text}<span>{projects.filter(p=>p.status===stage).length}</span></h3>{projects.filter(p=>p.status===stage).map(p=>{
 const related=tasks.filter(t=>t.project_id===p.id),done=related.filter(t=>t.done).length;
 const late=!!p.deadline&&new Date(p.deadline)<new Date()&&p.status!=="done";
 return <article className="pf-property" key={p.id}><button type="button" className="text-left font-bold" onClick={()=>onNavigate("projects",p.id)}>{p.name} ↗</button><span>{customers.find(c=>c.id===p.customer_id)?.name??"Client à relier"}</span><span className={late?"text-red-fg":""}>{p.deadline?`${late?"En retard · ":"Livraison · "}${p.deadline}`:"Échéance non renseignée"}</span><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-line" role="progressbar" aria-valuemin={0} aria-valuemax={related.length||1} aria-valuenow={done} aria-label="Tâches terminées"><div className="h-full rounded-full bg-accent" style={{width:related.length?`${done/related.length*100}%`:"0%"}}/></div><span>{done}/{related.length} tâches terminées</span>{related.map(t=><div key={t.id} className="border-t border-line pt-2"><label className="flex items-start gap-2 text-xs"><input type="checkbox" checked={t.done} onChange={e=>void onTask(t.id,{done:e.target.checked})}/>{t.title}</label>{!t.done&&<Button size="sm" variant="ghost" onClick={()=>void onTask(t.id,{blocked:!t.blocked})}>{t.blocked?"Débloquer la tâche":"Signaler un blocage"}</Button>}{t.blocked&&!t.done&&<p className="text-xs text-red-fg">Tâche bloquée</p>}</div>)}{sites.filter(s=>s.project_id===p.id).map(s=><button type="button" className="text-left text-xs text-green-fg" key={s.id} onClick={()=>onNavigate("sites",s.id)}>↗ {s.domain_name||"Site client"} · {s.domain_renewal_date?`Domaine : ${s.domain_renewal_date}`:"Renouvellement à renseigner"}</button>)}<div className="flex flex-wrap gap-1">{stages.filter(s=>s!==stage).map(s=><Button key={s} size="sm" variant="outline" onClick={()=>void onProject(p.id,{status:s})}>{PROJECT_STATUS_LABEL[s].text}</Button>)}<Button size="sm" variant="ghost" onClick={()=>onNavigate("invoices")}>Facturation →</Button></div></article>;
 })}</div>)}</div>}</section>;
}
