-- Seed du catalogue de métiers (98 professions, 16 familles) à partir de
-- web/js/categories.js — porté en base pour être réellement cherchable
-- (recherche floue via search_text, cf. 0002_workspaces.sql) au lieu d'un fichier
-- JS statique. Architecture pensée pour scaler à des milliers de lignes sans
-- changement de code UI : ajouter un métier = une ligne INSERT, rien d'autre.

insert into public.business_categories (slug, name, sort_order) values
  ('hebergement-tourisme', 'Hébergement & tourisme', 0),
  ('restauration', 'Restauration', 1),
  ('commerce-alimentaire', 'Commerce alimentaire', 2),
  ('commerce', 'Commerce', 3),
  ('beaute-bien-etre', 'Beauté & bien-être', 4),
  ('sport-loisirs', 'Sport & loisirs', 5),
  ('immobilier', 'Immobilier', 6),
  ('sante', 'Santé', 7),
  ('automobile', 'Automobile', 8),
  ('btp-artisans', 'BTP & artisans', 9),
  ('services-b2b', 'Services B2B', 10),
  ('numerique-communication', 'Numérique & communication', 11),
  ('transport-logistique', 'Transport & logistique', 12),
  ('services-locaux', 'Services locaux', 13),
  ('bien-etre-therapies', 'Bien-être & thérapies', 14),
  ('education-sport', 'Éducation & sport', 15)
on conflict (slug) do nothing;

insert into public.business_categories (parent_id, slug, name, icon, naf_codes, keywords, sort_order) values
  ((select id from public.business_categories where slug = 'hebergement-tourisme' and parent_id is null), 'hotels', 'Hôtels', '🏨', array['55.10Z']::text[], array['hotels']::text[], 0),
  ((select id from public.business_categories where slug = 'hebergement-tourisme' and parent_id is null), 'gites', 'Gîtes & hébergements touristiques', '🛏', array['55.20Z']::text[], array['gites','hebergements','touristiques']::text[], 1),
  ((select id from public.business_categories where slug = 'hebergement-tourisme' and parent_id is null), 'campings', 'Campings', '⛺', array['55.30Z']::text[], array['campings']::text[], 2),
  ((select id from public.business_categories where slug = 'hebergement-tourisme' and parent_id is null), 'travel', 'Agences de voyage', '✈️', array['79.11Z']::text[], array['agences','voyage']::text[], 3),
  ((select id from public.business_categories where slug = 'restauration' and parent_id is null), 'restaurants', 'Restaurants', '🍽', array['56.10A','56.10B','56.10C']::text[], array['restaurants','restaurant','resto']::text[], 4),
  ((select id from public.business_categories where slug = 'restauration' and parent_id is null), 'fastfood', 'Restauration rapide', '🍔', array['56.10C']::text[], array['restauration','rapide']::text[], 5),
  ((select id from public.business_categories where slug = 'restauration' and parent_id is null), 'bars', 'Bars & cafés', '☕', array['56.30Z']::text[], array['bars','cafes']::text[], 6),
  ((select id from public.business_categories where slug = 'restauration' and parent_id is null), 'catering', 'Traiteurs', '🥂', array['56.21Z']::text[], array['traiteurs']::text[], 7),
  ((select id from public.business_categories where slug = 'commerce-alimentaire' and parent_id is null), 'bakery', 'Boulangeries', '🥖', array['10.71C']::text[], array['boulangeries','boulanger','boulangerie']::text[], 8),
  ((select id from public.business_categories where slug = 'commerce-alimentaire' and parent_id is null), 'butcher', 'Boucheries', '🥩', array['47.22Z']::text[], array['boucheries']::text[], 9),
  ((select id from public.business_categories where slug = 'commerce-alimentaire' and parent_id is null), 'fish', 'Poissonneries', '🐟', array['47.23Z']::text[], array['poissonneries']::text[], 10),
  ((select id from public.business_categories where slug = 'commerce-alimentaire' and parent_id is null), 'wine', 'Cavistes', '🍇', array['47.25Z']::text[], array['cavistes']::text[], 11),
  ((select id from public.business_categories where slug = 'commerce-alimentaire' and parent_id is null), 'cheese', 'Fromageries', '🧀', array['47.29Z']::text[], array['fromageries']::text[], 12),
  ((select id from public.business_categories where slug = 'commerce-alimentaire' and parent_id is null), 'organic', 'Magasins bio', '🌿', array['47.29Z']::text[], array['magasins','bio']::text[], 13),
  ((select id from public.business_categories where slug = 'commerce' and parent_id is null), 'supermarkets', 'Supermarchés', '🛒', array['47.11D','47.11F']::text[], array['supermarches']::text[], 14),
  ((select id from public.business_categories where slug = 'commerce' and parent_id is null), 'convenience', 'Supérettes & épiceries', '🏪', array['47.11B','47.11C']::text[], array['superettes','epiceries']::text[], 15),
  ((select id from public.business_categories where slug = 'commerce' and parent_id is null), 'clothing', 'Magasins de vêtements', '👕', array['47.71Z']::text[], array['magasins','vetements']::text[], 16),
  ((select id from public.business_categories where slug = 'commerce' and parent_id is null), 'shoes', 'Magasins de chaussures', '👟', array['47.72A']::text[], array['magasins','chaussures']::text[], 17),
  ((select id from public.business_categories where slug = 'commerce' and parent_id is null), 'furniture', 'Magasins de meubles', '🛋', array['47.59A']::text[], array['magasins','meubles']::text[], 18),
  ((select id from public.business_categories where slug = 'commerce' and parent_id is null), 'florists', 'Fleuristes', '💐', array['47.76Z']::text[], array['fleuristes']::text[], 19),
  ((select id from public.business_categories where slug = 'commerce' and parent_id is null), 'bookstores', 'Librairies', '📚', array['47.61Z']::text[], array['librairies']::text[], 20),
  ((select id from public.business_categories where slug = 'commerce' and parent_id is null), 'jewelry', 'Bijouteries', '💎', array['47.77Z']::text[], array['bijouteries']::text[], 21),
  ((select id from public.business_categories where slug = 'commerce' and parent_id is null), 'toys', 'Magasins de jouets', '🧸', array['47.65Z']::text[], array['magasins','jouets']::text[], 22),
  ((select id from public.business_categories where slug = 'commerce' and parent_id is null), 'hardware', 'Quincailleries & bricolage', '🧰', array['47.52A','47.52B']::text[], array['quincailleries','bricolage']::text[], 23),
  ((select id from public.business_categories where slug = 'commerce' and parent_id is null), 'decor', 'Décoration & maison', '🏺', array['47.59B']::text[], array['decoration','maison']::text[], 24),
  ((select id from public.business_categories where slug = 'commerce' and parent_id is null), 'phone', 'Téléphonie & électronique', '📱', array['47.42Z','47.43Z']::text[], array['telephonie','electronique']::text[], 25),
  ((select id from public.business_categories where slug = 'beaute-bien-etre' and parent_id is null), 'hair', 'Coiffeurs', '✂️', array['96.02A']::text[], array['coiffeurs','coiffure','coiffeur','barbier','salon de coiffure']::text[], 26),
  ((select id from public.business_categories where slug = 'beaute-bien-etre' and parent_id is null), 'beauty', 'Instituts de beauté', '✨', array['96.02B']::text[], array['instituts','beaute']::text[], 27),
  ((select id from public.business_categories where slug = 'beaute-bien-etre' and parent_id is null), 'spa', 'Centres bien-être / spa', '🧖', array['96.04Z']::text[], array['centres','bien','etre','spa']::text[], 28),
  ((select id from public.business_categories where slug = 'beaute-bien-etre' and parent_id is null), 'tattoo', 'Tatoueurs', '🖋', array['96.09Z']::text[], array['tatoueurs']::text[], 29),
  ((select id from public.business_categories where slug = 'sport-loisirs' and parent_id is null), 'gyms', 'Salles de sport', '🏋️', array['93.13Z']::text[], array['salles','sport','salle de sport','fitness']::text[], 30),
  ((select id from public.business_categories where slug = 'sport-loisirs' and parent_id is null), 'sportsclubs', 'Clubs de sport', '⚽', array['93.12Z']::text[], array['clubs','sport']::text[], 31),
  ((select id from public.business_categories where slug = 'sport-loisirs' and parent_id is null), 'events', 'Organisateurs d’événements', '🎪', array['82.30Z']::text[], array['organisateurs','evenements']::text[], 32),
  ((select id from public.business_categories where slug = 'immobilier' and parent_id is null), 'realestate', 'Agences immobilières', '🏢', array['68.31Z']::text[], array['agences','immobilieres','agence immobiliere','immobilier']::text[], 33),
  ((select id from public.business_categories where slug = 'immobilier' and parent_id is null), 'propertymgmt', 'Syndics & administrateurs de biens', '🏘', array['68.32A']::text[], array['syndics','administrateurs','biens']::text[], 34),
  ((select id from public.business_categories where slug = 'immobilier' and parent_id is null), 'developers', 'Promoteurs immobiliers', '🏙', array['41.10A','41.10B','41.10C','41.10D']::text[], array['promoteurs','immobiliers']::text[], 35),
  ((select id from public.business_categories where slug = 'sante' and parent_id is null), 'medical', 'Médecins généralistes', '🩺', array['86.21Z']::text[], array['medecins','generalistes']::text[], 36),
  ((select id from public.business_categories where slug = 'sante' and parent_id is null), 'specialists', 'Médecins spécialistes', '🧑‍⚕️', array['86.22A','86.22B','86.22C']::text[], array['medecins','specialistes']::text[], 37),
  ((select id from public.business_categories where slug = 'sante' and parent_id is null), 'dentists', 'Cabinets dentaires', '🦷', array['86.23Z']::text[], array['cabinets','dentaires','dentiste','cabinet dentaire']::text[], 38),
  ((select id from public.business_categories where slug = 'sante' and parent_id is null), 'nurses', 'Infirmiers', '💉', array['86.90D']::text[], array['infirmiers']::text[], 39),
  ((select id from public.business_categories where slug = 'sante' and parent_id is null), 'physio', 'Kinésithérapeutes', '🦵', array['86.90E']::text[], array['kinesitherapeutes']::text[], 40),
  ((select id from public.business_categories where slug = 'sante' and parent_id is null), 'osteo', 'Ostéopathes & autres soins', '👐', array['86.90F']::text[], array['osteopathes','autres','soins']::text[], 41),
  ((select id from public.business_categories where slug = 'sante' and parent_id is null), 'labs', 'Laboratoires d’analyses', '🧪', array['86.90B']::text[], array['laboratoires','analyses']::text[], 42),
  ((select id from public.business_categories where slug = 'sante' and parent_id is null), 'pharmacy', 'Pharmacies', '💊', array['47.73Z']::text[], array['pharmacies']::text[], 43),
  ((select id from public.business_categories where slug = 'sante' and parent_id is null), 'opticians', 'Opticiens', '👓', array['47.78A']::text[], array['opticiens']::text[], 44),
  ((select id from public.business_categories where slug = 'sante' and parent_id is null), 'vets', 'Vétérinaires', '🐾', array['75.00Z']::text[], array['veterinaires','veterinaire']::text[], 45),
  ((select id from public.business_categories where slug = 'sante' and parent_id is null), 'ambulance', 'Ambulances', '🚑', array['86.90A']::text[], array['ambulances']::text[], 46),
  ((select id from public.business_categories where slug = 'automobile' and parent_id is null), 'garages', 'Garages automobiles', '🔧', array['45.20A','45.20B']::text[], array['garages','automobiles','garagiste','mecanicien','mecanique auto','entretien voiture']::text[], 47),
  ((select id from public.business_categories where slug = 'automobile' and parent_id is null), 'dealers', 'Concessions automobiles', '🚗', array['45.11Z']::text[], array['concessions','automobiles']::text[], 48),
  ((select id from public.business_categories where slug = 'automobile' and parent_id is null), 'motorcycle', 'Motos & deux-roues', '🏍', array['45.40Z']::text[], array['motos','deux','roues']::text[], 49),
  ((select id from public.business_categories where slug = 'automobile' and parent_id is null), 'carrental', 'Location de voitures', '🚙', array['77.11A','77.11B']::text[], array['location','voitures']::text[], 50),
  ((select id from public.business_categories where slug = 'automobile' and parent_id is null), 'drivingschool', 'Auto-écoles', '🚘', array['85.53Z']::text[], array['auto','ecoles']::text[], 51),
  ((select id from public.business_categories where slug = 'automobile' and parent_id is null), 'bodyshop', 'Carrosseries', '🛠', array['45.20A']::text[], array['carrosseries']::text[], 52),
  ((select id from public.business_categories where slug = 'automobile' and parent_id is null), 'tyres', 'Pneus & centres auto', '🛞', array['45.32Z']::text[], array['pneus','centres','auto']::text[], 53),
  ((select id from public.business_categories where slug = 'automobile' and parent_id is null), 'carwash', 'Lavage automobile', '🧽', array['45.20A']::text[], array['lavage','automobile']::text[], 54),
  ((select id from public.business_categories where slug = 'btp-artisans' and parent_id is null), 'plumbing', 'Plombiers', '🔩', array['43.22A']::text[], array['plombiers','plombier','plomberie']::text[], 55),
  ((select id from public.business_categories where slug = 'btp-artisans' and parent_id is null), 'heating', 'Chauffagistes', '🔥', array['43.22B']::text[], array['chauffagistes']::text[], 56),
  ((select id from public.business_categories where slug = 'btp-artisans' and parent_id is null), 'electric', 'Électriciens', '⚡', array['43.21A']::text[], array['electriciens','electricien','electricite']::text[], 57),
  ((select id from public.business_categories where slug = 'btp-artisans' and parent_id is null), 'roofing', 'Couvreurs', '🏠', array['43.91B']::text[], array['couvreurs']::text[], 58),
  ((select id from public.business_categories where slug = 'btp-artisans' and parent_id is null), 'painting', 'Peintres en bâtiment', '🎨', array['43.34Z']::text[], array['peintres','batiment']::text[], 59),
  ((select id from public.business_categories where slug = 'btp-artisans' and parent_id is null), 'masonry', 'Maçons', '🧱', array['43.99C']::text[], array['macons']::text[], 60),
  ((select id from public.business_categories where slug = 'btp-artisans' and parent_id is null), 'carpentry', 'Menuisiers', '🪚', array['43.32A']::text[], array['menuisiers']::text[], 61),
  ((select id from public.business_categories where slug = 'btp-artisans' and parent_id is null), 'flooring', 'Carreleurs', '◫', array['43.33Z']::text[], array['carreleurs']::text[], 62),
  ((select id from public.business_categories where slug = 'btp-artisans' and parent_id is null), 'insulation', 'Isolation', '🧤', array['43.29A']::text[], array['isolation']::text[], 63),
  ((select id from public.business_categories where slug = 'btp-artisans' and parent_id is null), 'architects', 'Architectes', '📐', array['71.11Z']::text[], array['architectes']::text[], 64),
  ((select id from public.business_categories where slug = 'btp-artisans' and parent_id is null), 'landscape', 'Paysagistes', '🌿', array['81.30Z']::text[], array['paysagistes']::text[], 65),
  ((select id from public.business_categories where slug = 'btp-artisans' and parent_id is null), 'locksmith', 'Serruriers', '🔐', array['43.32B']::text[], array['serruriers']::text[], 66),
  ((select id from public.business_categories where slug = 'btp-artisans' and parent_id is null), 'solar', 'Installateurs photovoltaïques', '☀️', array['43.21A']::text[], array['installateurs','photovoltaiques']::text[], 67),
  ((select id from public.business_categories where slug = 'btp-artisans' and parent_id is null), 'pools', 'Piscinistes', '🏊', array['43.99D']::text[], array['piscinistes']::text[], 68),
  ((select id from public.business_categories where slug = 'btp-artisans' and parent_id is null), 'kitchens', 'Cuisinistes', '🍳', array['43.32A']::text[], array['cuisinistes']::text[], 69),
  ((select id from public.business_categories where slug = 'services-b2b' and parent_id is null), 'cleaning', 'Entreprises de nettoyage', '🧹', array['81.21Z','81.22Z']::text[], array['entreprises','nettoyage']::text[], 70),
  ((select id from public.business_categories where slug = 'services-b2b' and parent_id is null), 'security', 'Sécurité privée', '🔒', array['80.10Z']::text[], array['securite','privee']::text[], 71),
  ((select id from public.business_categories where slug = 'services-b2b' and parent_id is null), 'recruitment', 'Cabinets de recrutement', '🧑‍💼', array['78.10Z']::text[], array['cabinets','recrutement']::text[], 72),
  ((select id from public.business_categories where slug = 'services-b2b' and parent_id is null), 'accounting', 'Cabinets comptables', '🧾', array['69.20Z']::text[], array['cabinets','comptables']::text[], 73),
  ((select id from public.business_categories where slug = 'services-b2b' and parent_id is null), 'law', 'Avocats', '⚖️', array['69.10Z']::text[], array['avocats']::text[], 74),
  ((select id from public.business_categories where slug = 'services-b2b' and parent_id is null), 'insurance', 'Assurances & courtiers', '🛡', array['66.22Z']::text[], array['assurances','courtiers']::text[], 75),
  ((select id from public.business_categories where slug = 'services-b2b' and parent_id is null), 'consulting', 'Cabinets de conseil', '🧠', array['70.22Z']::text[], array['cabinets','conseil']::text[], 76),
  ((select id from public.business_categories where slug = 'numerique-communication' and parent_id is null), 'web', 'Agences web & développement', '💻', array['62.01Z','62.02A']::text[], array['agences','web','developpement','agence web','creation site internet','developpement web']::text[], 77),
  ((select id from public.business_categories where slug = 'numerique-communication' and parent_id is null), 'it', 'Prestataires informatiques', '🖥', array['62.02A','62.09Z']::text[], array['prestataires','informatiques']::text[], 78),
  ((select id from public.business_categories where slug = 'numerique-communication' and parent_id is null), 'marketing', 'Agences marketing / publicité', '📣', array['73.11Z']::text[], array['agences','marketing','publicite']::text[], 79),
  ((select id from public.business_categories where slug = 'numerique-communication' and parent_id is null), 'design', 'Designers & graphistes', '🖌', array['74.10Z']::text[], array['designers','graphistes']::text[], 80),
  ((select id from public.business_categories where slug = 'numerique-communication' and parent_id is null), 'photo', 'Photographes', '📷', array['74.20Z']::text[], array['photographes']::text[], 81),
  ((select id from public.business_categories where slug = 'transport-logistique' and parent_id is null), 'transport', 'Transport routier', '🚚', array['49.41A','49.41B','49.41C']::text[], array['transport','routier']::text[], 82),
  ((select id from public.business_categories where slug = 'transport-logistique' and parent_id is null), 'moving', 'Déménagement', '📦', array['49.42Z']::text[], array['demenagement']::text[], 83),
  ((select id from public.business_categories where slug = 'transport-logistique' and parent_id is null), 'taxi', 'Taxis & VTC', '🚕', array['49.32Z']::text[], array['taxis','vtc']::text[], 84),
  ((select id from public.business_categories where slug = 'services-locaux' and parent_id is null), 'funeral', 'Pompes funèbres', '🕊', array['96.03Z']::text[], array['pompes','funebres']::text[], 85),
  ((select id from public.business_categories where slug = 'services-locaux' and parent_id is null), 'laundry', 'Pressings & blanchisseries', '👔', array['96.01B']::text[], array['pressings','blanchisseries']::text[], 86),
  ((select id from public.business_categories where slug = 'services-locaux' and parent_id is null), 'repair', 'Réparation informatique / appareils', '🛠', array['95.11Z','95.22Z']::text[], array['reparation','informatique','appareils']::text[], 87),
  ((select id from public.business_categories where slug = 'services-locaux' and parent_id is null), 'petgroom', 'Toiletteurs', '🐶', array['96.09Z']::text[], array['toiletteurs']::text[], 88),
  ((select id from public.business_categories where slug = 'bien-etre-therapies' and parent_id is null), 'sophrology', 'Sophrologues', '🧘', array['86.90F']::text[], array['sophrologues']::text[], 89),
  ((select id from public.business_categories where slug = 'bien-etre-therapies' and parent_id is null), 'naturopathy', 'Naturopathes', '🌿', array['86.90F']::text[], array['naturopathes']::text[], 90),
  ((select id from public.business_categories where slug = 'bien-etre-therapies' and parent_id is null), 'hypnosis', 'Hypnothérapeutes', '◉', array['86.90F']::text[], array['hypnotherapeutes']::text[], 91),
  ((select id from public.business_categories where slug = 'bien-etre-therapies' and parent_id is null), 'digitopuncture', 'Digitopuncture / digipuncture', '✋', array['86.90F']::text[], array['digitopuncture','digipuncture','digitoponcture']::text[], 92),
  ((select id from public.business_categories where slug = 'bien-etre-therapies' and parent_id is null), 'massage', 'Massage bien-être', '💆', array['96.04Z']::text[], array['massage','bien','etre']::text[], 93),
  ((select id from public.business_categories where slug = 'beaute-bien-etre' and parent_id is null), 'barbers', 'Barbiers', '🧔', array['96.02A']::text[], array['barbiers']::text[], 94),
  ((select id from public.business_categories where slug = 'beaute-bien-etre' and parent_id is null), 'nails', 'Ongleries / prothésistes ongulaires', '💅', array['96.02B']::text[], array['ongleries','prothesistes','ongulaires']::text[], 95),
  ((select id from public.business_categories where slug = 'education-sport' and parent_id is null), 'dance', 'Écoles de danse', '💃', array['85.52Z']::text[], array['ecoles','danse']::text[], 96),
  ((select id from public.business_categories where slug = 'education-sport' and parent_id is null), 'yoga', 'Yoga / pilates', '🧘', array['85.51Z']::text[], array['yoga','pilates']::text[], 97)
on conflict (slug) do nothing;
